instances:
  # list of instances to be monitored
  - name: "<name used in the metric label app_instance>"
    url: "<Full qualified URL which should be monitored>"
    shortname: "<abbreviated name>"
version_metrics:
  interval: <value in seconds, how often the version is polled>
  endpoint: "<URL suffix used to get the version info>"
maintenance_metrics:
  window_refresh_interval_min: <value in minutes, how often the maintenance windows are polled from the terraform state>
  metric_refresh_interval_sec: <value in seconds, how often the metric is refreshed>
  nodepool_maintenance_duration_min: <value in minutes, duration of a nodepool maintenance>
  cluster_maintenance_duration_min: <value in minutes, duration of a cluster maintenance>
  s3_stage_directory: "<Prefix for the terraform state s3 object, for example: env:/dev/>"
  s3_endpoint: "<S3 endpoint for the terraform state bucket>"
  s3_bucket: "<Name of the terraform state bucket>"
planned_maintenance_metrics:
  window_refresh_interval_min: <value in minutes, how often the maintenance windows are polled from Cachet>
  metric_refresh_interval_sec: <value in seconds, how often the metric is refreshed>
  default_maintenance_duration_min: <value in minutes, duration of a maintenance without specified end time>
  cachet_timezone: "<timezone of the cachet servers, for example Europe/Berlin>"
  # list of cachet pages
  platforms:
    - name: "<platform name>"
      url: "<Base URL of the cachet page, for example: https://status.example.org>"
uptime_kuma_maintenance_metrics:
  api_url: "<Base URL of the Uptime kuma page, for example: https://status.example.org>"
  timezone: "<timezone of the Uptime kuma servers, for example Europe/Berlin>"
  metric_refresh_interval_sec: <value in seconds, how often the metric is refreshed>
storage_metrics:
  url: "<URL of the S3 endpoint for the bucket>"
  region: "<Region of the bucket>"
  bucket_name: "<Name of the bucket>"
  availability:
    enabled: <Monitoring availability: true/false>
    interval_sec: <value in seconds, how often availability is checked>
  stats:
    enabled: <Fetching bucket stats: true/false>
    interval_min: <value in minutes, how often the bucket stats are fetched>
    exclude_subfolders: <Only metrics for top-level folders: true/false>
    retries: <how often a failed request is retried before the fetching run is aborted>
    backoff_sec: <value in seconds, how long to wait between the retries>
