features:
  version_metrics: enabled
instances:
  - Brandenburg:
    url: "https://brandenburg.cloud"
    shortname: "brb"
  - Niedersachsen:
    url: "https://niedersachsen.cloud"
    shortname: "nbc"
  - Thueringen:
    url: "https://schulcloud-thueringen.de"
    shortname: "thr"
  - International:
    url: "https://international.hpi-schul-cloud.de"
    shortname: "int"
  - dBildungscloud:
    url: "https://dbildungscloud.de"
    shortname: "dbc"
  - Demo:
    url: "https://demo.hpi-schul-cloud.de"
    shortname: "demo"
version_metrics:
  url_suffix:
    server: /api/v1/version
    client: /version
    nuxt: /nuxtversion