rest:
  url: "https://example.org/primenumbers/v1"
  port: 8443
prime_numbers: [2, 3, 5, 7, 11, 13, 17, 19]
instances:
  - Brandenburg:
    url: "https://brandenburg.cloud"
    shortname: "brb"
  - Niedersachsen:
    url: "https://niedersachsen.cloud"
    shortname: "nbc"
