sc_tunnel_configuration:
  #
  # Default configuration, can be overwritten by config in current users home .config folder, environment variables or parameters
  jumphost: 
  jumphost_user:
  ionos_username:
  ionos_password:
  