---
collections:
  - name: awx.awx
  - name: kubernetes.core
    version: 2.1.1
  - name: ansible.posix
    version: 1.5.1
    # testen ob notwendig 
  # - name: ansible.windows
  - name: community.general
    version: 5.3.0
