---
collections:
  - name: awx.awx
  - name: kubernetes.core
  - name: ansible.posix
  - name: ansible.windows
  - name: community.general
roles:
  - name: geerlingguy.docker
    version: 6.0.4
  - name: geerlingguy.certbot
    version: 5.0.2