---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        haproxy_frontend_ips: [ 10.0.4.8 ]
        haproxy_frontend_network_interfaces: [ frontend ]
        haproxy_frontend_open_ports: [ "80" ]
        haproxy_backend_ips: [ 10.0.6.8 ]
        haproxy_backend_network_interfaces: [ backend ]
        haproxy_backend_open_ports: [ "9100" ]
        haproxy_config_template: backend-haproxy.cfg.j2
        haproxy_default_mode: http
verifier:
  name: ansible
