---
- name: Prepare
  hosts: instance
  tasks:
    - name: Install firewalld
      yum:
        name: firewalld
        state: present
    - name: Start firewalld
      service:
        name: firewalld
        enabled: true
        state: started
    - name: Create frontend dummy interface
      command: ip link add {{ haproxy_frontend_network_interfaces[0] }} type dummy
    - name: Create backend dummy interface
      command: ip link add {{ haproxy_backend_network_interfaces[0] }} type dummy
    - name: Set frontend IP
      command: ip addr add {{ item }} dev {{ haproxy_frontend_network_interfaces[0] }}
      with_items: "{{ haproxy_frontend_ips }}"
    - name: Set backend IP
      command: ip addr add {{ item }} dev {{ haproxy_backend_network_interfaces[0] }}
      with_items: "{{ haproxy_backend_ips }}"
    - name: Interface {{ haproxy_frontend_network_interfaces[0] }} in zone public
      command: firewall-cmd --zone=public --change-interface={{ haproxy_frontend_network_interfaces[0] }}
    - name: Interface {{ haproxy_backend_network_interfaces[0] }} in zone public
      command: firewall-cmd --zone=public --change-interface={{ haproxy_backend_network_interfaces[0] }}
      
