---
# Currently fail with docker provisioner since the firewalld behavior is different from IONOS
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: haproxy enabled and running
    service:
      name: haproxy
      state: started
      enabled: yes
  # On IONOS VMs change-interface works immediately but in docker containers firewalld must first be restarted
  - name: restart firewalld
    service:
      name: firewalld
      state: restarted
  - name: zones created
    shell: firewall-cmd --get-zones | grep -q {{ item }}
    with_items: [ frontend, backend ]
  - name: frontend has correct interface
    shell: firewall-cmd --zone=frontend --list-interfaces | grep -q '^{{ haproxy_frontend_network_interfaces[0] }}$'
  - name: backend has correct interface
    shell: firewall-cmd --zone=backend --list-interfaces | grep -q '^{{ haproxy_backend_network_interfaces[0] }}$'
  - name: frontend has correct port open
    shell: firewall-cmd --zone=frontend --list-ports | grep -q '{{ item }}/tcp'
    with_items: "{{ haproxy_frontend_open_ports }}"
  - name: frontend has correct port open
    shell: firewall-cmd --zone=backend --list-ports | grep -q '{{ item }}/tcp'
    with_items: "{{ haproxy_backend_open_ports }}"
  - name: zones have no services
    shell: firewall-cmd --zone={{ item }} --list-services | grep -q '^$'
    with_items: [ frontend, backend ]
  - name: zones have no protocols
    shell: firewall-cmd --zone={{ item }} --list-protocols | grep -q '^$'
    with_items: [ frontend, backend ]
  - name: zones have no rich rules
    shell: firewall-cmd --zone={{ item }} --list-rich-rules | grep -q '^$'
    with_items: [ frontend, backend ]
