---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: "quay.io/ansible/ansible-runner:stable-2.12-latest"
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
additional_build_steps:
  prepend: |
    RUN whoami
    RUN cat /etc/os-release
    RUN pip3 install --upgrade pip setuptools
  append:
    - RUN alternatives --set python /usr/bin/python3
