haproxy_exporter_version: 0.10.0
# Default haproxy config
haproxy_config_template: haproxy.cfg.j2
# Backend haproxy config
#haproxy_config_template: backend-haproxy.cfg.j2
install_haproxy_tools: true
install_haproxy_debuginfo: false

# haproxy settings
haproxy_maxconn: 180000
haproxy_maxsessrate: 2048

# backend-haproxy.cfg.j2 variables
haproxy_strict_limits: true
haproxy_default_mode: http
haproxy_default_log: global
haproxy_options:
    - dontlognull
    - dontlog-normal
    - httplog
    - http-server-close
    - redispatch
haproxy_retries: 3
haproxy_timeout_http_request: 10s
haproxy_timeout_queue: 5s
haproxy_timeout_connect: 10s
haproxy_timeout_client: 30s
haproxy_timeout_server: 30s
haproxy_timeout_http_keep_alive: 2s
haproxy_timeout_check: 10s
haproxy_timeout_client_fin: 1s
haproxy_timeout_server_fin: 1s
haproxy_frontend_network_interfaces: []
firewall_frontend_open_ports: [ "22","80" ]
haproxy_frontend_ports: [ "80" ]
haproxy_backend_network_interfaces: []
firewall_backend_open_ports: [ "9100", "9101" ]
haproxy_backend_ports: [ "9100", "9101" ]
haproxy_frontend_ips: []
haproxy_k8s_node_ips: []
# optional variables
  # haproxy_maxsslconn: 180000
  # haproxy_tune_ssl_cachesize: 1000000
  # haproxy_tune_ssl_default_dh_param: 2048
  # haproxy_ssl_default_bind_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
  # haproxy_ssl_default_bind_options: no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
  # haproxy_ssl_default_server_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
  # haproxy_ssl_default_server_options: no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

# sysctl settings
sysctl_fs_file_max: "10240"
sysctl_net_core_somaxconn: "2048"
sysctl_net_core_netdev_max_backlog: "2048"
sysctl_vm_swappiness:  "20"
sysctl_nf_conntrack_hashsize: "500000"
