---
  - name: Create privatelan zone
    ansible.posix.firewalld:
      zone: privatelan
      state: present
      permanent: true
    register: create_privatelan

  - name: reload firewall-cmd
    command: firewall-cmd --reload
    when: create_privatelan.changed

  - name: Open port 80 in privatelan
    ansible.posix.firewalld:
      port: 80/tcp
      zone: privatelan
      state: enabled
      permanent: true
      immediate: true

  - name: Add network interfaces to privatelan
    command: firewall-cmd --permanent --zone=privatelan --change-interface={{ item }}
    with_items: "{{  privatelan_network_interfaces  }}"
    when: create_privatelan.changed
