name: Build and push Docker Image on Tag

on:
  push:
    tags:
      - "infra-tools-*.*.*"
      - "infra-tools-debian-*.*.*"
      - "dbcmetrics-*.*.*"
      - "awx-ee-*.*.*"
      - "cron-tools-*.*.*"
      - "cron-tools-debian-*.*.*"

jobs:
  pre_build:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.extract.outputs.image_name }}
    steps:
      - name: Extract image name from tag
        id: extract
        run: |
          IMAGE_NAME="$(echo "${GITHUB_REF_NAME}" | sed -E 's/-[0-9]+\.[0-9]+\.[0-9]+$//')"
          echo "image_name=${IMAGE_NAME}" >> "$GITHUB_OUTPUT"
          echo "Image name: ${IMAGE_NAME}"

  build_and_push:
    needs: pre_build
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@7
    permissions:
      packages: write
      contents: read
      security-events: write
    with:
      image_name: ${{ needs.pre_build.outputs.image_name }}
      container_registry: "ghcr.io"
      add_latest_tag: true
      image_tag_generation: "mmp_git_tag,mm_git_tag"
      context: ./${{ needs.pre_build.outputs.image_name }}
      run_trivy_scan: false
      run_clamav_scan: false
      limit-severities-for-sarif: false
    secrets: inherit