---
name: Build and push Docker image

on:
  push:
    tags:
      - '[0-9]*'
jobs:
  build_and_push:
    runs-on: ubuntu-18.04
    if: (contains(github.event.head_commit.message, '[skip ci]') == false) && (github.event_name == 'push')
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: make build
        working-directory: infra-tools

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image
        run: make push
        working-directory: infra-tools
