---
name: Build and push Docker Image

on:
  workflow_call:
    inputs:
      registry:
        description: "Docker registry where the image will be pushed, options are dockerhub (default) and ghcr"
        required: false
        default: "dockerhub"
        type: string
      image:
        description: "Image to build"
        required: true
        type: string
      tag:
        description: "Tag of the image to build"
        required: true
        type: string
      context:
        description: "Directory where the image is built, defaults to repository root"
        required: false
        default: "./"
        type: string
    secrets:
      DOCKER_USERNAME:
        required: false
      DOCKER_TOKEN:
        required: false

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Ghcr needs "ghcr.io/" prefix and dockerhub doesn't need a prefix
      - name: Compute image name
        if: inputs.registry == "ghcr.io"
        id: image_prefix
        # run: if [[ ${{ inputs.registry }} = "ghcr.io" ]]; then echo "prefix=ghcr.io/"; else echo "prefix="; fi >> GITHUB_OUTPUT
        run: echo "prefix=ghcr.io/" >> GITHUB_OUTPUT

      - name: Docker meta Service Name for docker hub
        id: docker_meta_img_hub
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.image_prefix.outputs.prefix || "" }}${{ inputs.image }}
          tags: |
            type=semver,pattern={{version}},value=${{ inputs.tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.tag }}

      - name: Log into dockerhub
        if: inputs.registry == 'dockerhub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log into ghcr
        if: inputs.registry == 'ghcr.io'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ github.repository }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta_img_hub.outputs.tags }}
          labels: ${{ steps.docker_meta_img_hub.outputs.labels }}
