name: dbcmetrics Docker Image on Push to GHCR

on:
  push:
    branches-ignore:
      - main
    paths:
      - "dbcmetrics/**"

concurrency:
  group: dbcmetrics-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_image_on_push:
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@7
    with:
      image_name: "dbcmetrics"
      context: "./dbcmetrics/"
      image_tag_generation: "ticket_from_branch"
      add_latest_tag: false
      container_registry: "ghcr.io"
      run_trivy_scan: true
      run_clamav_scan: true
      limit-severities-for-sarif: false