---
name: dbcmetrics Docker Image on Push to GHCR

on:
  push:
    branches-ignore:
      - "master"
    paths:
      - "dbcmetrics"

jobs:
  build_and_push_docker_to_ghcr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker meta Service Name for docker hub
        id: docker_meta_img_hub
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository_owner }}/dbcmetrics
          tags: |
            type=raw,value=latest,prefix={{branch}}-

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ github.repository }}
        uses: docker/build-push-action@v2
        with:
          context: ./dbcmetrics/
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta_img_hub.outputs.tags }}
          labels: ${{ steps.docker_meta_img_hub.outputs.labels }}
