---
name: dbcmetrics Docker Image on Push to GHCR

on:
  push:
    branches-ignore:
      - master
    paths:
      - 'dbcmetrics/**'

jobs:
  skip_ci:
    runs-on: ubuntu-latest
    # Map the output to the job's outputs
    outputs:
      canSkip: ${{ steps.check.outputs.canSkip }}
    steps:
      - id: check
        uses: Legorooj/skip-ci@main

  build_and_push_docker_to_ghcr:
    # Wait for the skip_ci job to run
    needs: skip_ci
    # And only run the build if canSkip isn't 'true'.
    if: ${{ needs.skip_ci.outputs.canSkip != 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker meta Service Name for docker hub
        id: docker_meta_img_hub
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository_owner }}/dbcmetrics
          tags: |
            type=match,value={{branch}},pattern=.*\d,suffix=-latest

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ github.repository }}
        uses: docker/build-push-action@v2
        with:
          context: ./dbcmetrics/
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta_img_hub.outputs.tags }}
          labels: ${{ steps.docker_meta_img_hub.outputs.labels }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: ${{ steps.docker_meta_img_hub.outputs.tags }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
