---
name: docops Docker Image on Push to GHCR

on:
  push:
    tags:
      - 'docops-[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_image_on_push:
    permissions:
      packages: write
      security-events: write
      actions: read
      contents: read
    uses: ./.github/workflows/imagetoghcr-on-push.yaml
    with:
      image_name: "docops"
      context: "./docops/"
