---
name: Dummy Docker Image on Push to GHCR

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - 'awx-ee/**'
      - 'dbcmetrics/**'
      - 'infra-tools/**'

jobs:
  build_image_on_push:
    uses: ./github/workflows/dummy-reusable-workflow.yaml
    # runs-on: ubuntu-latest
    # steps:
    #   - name: build_and_push_docker_to_ghcr
    #     run: 'echo "No docker images to build" '
