---
name: Filter branch name for ticket and scope

on:
  workflow_call:
    inputs:
      branch_name:
        description: "Branch name to filter"
        required: true
        type: string
    outputs:
      ticket:
        value: ${{ jobs.job.outputs.ticket }}
      scope:
        value: ${{ jobs.job.outputs.ticket }}

jobs:
  job:
    runs-on: ubuntu-latest
    outputs:
      ticket: ${{ steps.ticket.outputs.ticket }}
      scope: ${{ steps.scope.outputs.scope }}
    steps:
      - name: Filter ticket
        id: ticket
        run: |
          echo "ticket=$(echo ${{ inputs.branch_name }} | grep -oE '[a-zA-Z]+-[0-9]+')" >> $GITHUB_OUTPUT
      - name: Filter scope
        id: scope
        run: |
          echo "scope=$(echo ${{ inputs.branch_name }} | grep -oE '[a-zA-Z]+-[0-9]+-[a-z]+' | grep -oE '[a-z]+$')" >> $GITHUB_OUTPUT
