---
name: infra-tools Docker Image on Push to GHCR

on:
  push:
    branches-ignore:
      - master
    paths:
      - 'infra-tools/**'

jobs:
  build_image_on_push:
    runs-on: ubuntu-latest
    steps:
    - run: 'pwd'
    - run: 'ls'
    - uses: ./.github/workflows/imagetoghcr-on-push.yaml
      with:
        image_name: "infra-tools"
