---
name: infra-tools Docker Image on Push to GHCR

on:
  push:
    branches-ignore:
      - master
    paths:
      - 'infra-tools/**'

jobs:
  build_image_on_push:
    uses: ./.github/workflows/imagetoghcr-on-push.yaml
