---
name: infra-tools Docker Image Trivy Image Vulnerability Scann Cron Job

on:
  schedule:
    # Runs "at 2 a.m. past every day" (see https://crontab.guru)
    - cron: '0 2 * * *'

jobs:
  build_image_on_push:
    uses: hpi-schul-cloud/infra-tools/.github/workflows/trivy-scan.yaml@OPS-3814-add-Image-Vulnerability-Scanning
    # uses: hpi-schul-cloud/infra-tools/.github/workflows/trivy-scan.yaml@master
    with:
      image-ref: 'docker.io/schulcloud/infra-tools:latest'



