---
name: Docker Image on Push to GHCR

on:
  push:
    branches-ignore:
      - master
    paths:
      - 'infra-tools/**'

jobs:
  call-workflow:
    uses: ./.github/workflows/imagetoghcr-on-push.yaml
    with:
      image_name: "infra-tools"
