---
name: Trigger AWX job

on:
  workflow_call:
    inputs:
      awxkit_version:
        description: "Version of awxkit to use"
        required: false
        default: 23.2.0
        type: string
      host:
        description: "The AWX host to trigger"
        required: false
        default: "https://awx.dbildungscloud.de"
        type: string
      job_id:
        description: "The ID of the AWX job to trigger"
        required: true
        type: string
      # The following inputs allow overriding job settings, this only works if the AWX job allows this, otherwise they are ignored
      job_type:
        description: "Playbook run or check"
        required: false
        default: run
        type: string
      limit:
        description: "Optional limit override, if empty uses the job default, not all hosts"
        required: false
        default: ""
        type: string
      # branch:
      #   description: "Optional branch override"
      #   required: false
      #   default: ""
      #   type: string
    secrets:
      AWX_TOKEN:
        required: true

jobs:
  run_awx:
    runs-on: ubuntu-latest
    steps:
      - name: Pip install awxkit
        run: |
          pip3 install awxkit==${{ inputs.awxkit_version }}
      - name: Run the job
        env:
          TOWER_HOST: ${{ inputs.host }}
          TOWER_OAUTH_TOKEN: ${{ secrets.AWX_TOKEN }}
        run: |
          # Needed to keep the exit code of the AWX command after piping the output to jq
          set -o pipefail
          # Only keep job URL, job status and detail which contains error messages
          # We don't use the awx jq output format because it doesn't show error messages
          awx job_template launch ${{ inputs.job_id }} --job_type ${{ inputs.job_type }} ${{ if inputs.limit != "" '--limit ' + inputs.limit }} --wait --interval 10 | jq '{"url": "https://awx.dbildungscloud.de/#/jobs/\(.job)", "status": .status, "detail": .detail }'
