name: Docker Image Trivy Image Vulnerability Scan Cron Job

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  security-events: write
  actions: read
  contents: read
  packages: read

jobs:
  trivy_image_scan_cron:
    strategy:
      fail-fast: false
      matrix:
        image:
          - infra-tools
          - infra-tools-debian
          - dbcmetrics
          - awx-ee
          - docops
          - cron-tools
          - cron-tools-debian

    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-trivy.yaml@8
    with:
      image_ref: "ghcr.io/dbildungsplattform/${{ matrix.image }}:latest"
      severity: "CRITICAL,HIGH"
      fail_on_vulnerabilites: true
      ignore-unfixed: true
      limit-severities-for-sarif: false